export { default as Navbar } from './Navbar/navbar';
export { default as Movies } from './Movies/movies';
export { default as MoviesTable } from './MoviesTable/moviesTable';
export { default as Rentals } from './Rentals/rentals';
export { default as Customers } from './Customers/customers';
export { default as LoginForm } from './LoginForm/loginForm';
export { default as RegisterForm } from './RegisterForm/registerForm';
export { default as MovieForm } from './MovieForm/movieForm';
export { default as Logout } from './Logout/logout';
